=== Bart0l/Freestyle-XML-XSD/Freestyle.xsd
<?xml version="1.0" encoding="ISO-8859-2"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="projekt" type="projekt-typ"/> 
  <xs:element name="edycja" type="edycja-type"/> 
  <xs:element name="Wersy_dnia" type="Wersy_dnia-type"/> 
  <xs:element name="Mistrzowie" type="Mistrzowie-type"/>  
  <xs:element name="Koncerty" type="Koncerty-type"/>  
  <xs:element name="Wykonawcy" type="Wykonawcy-type"/>
  <xs:element name="Informacje" type="Informacje-type"/>  
  <xs:element name="Kontakt" type="Kontakt-type"/> 
  <xs:element name="autor" type="autor-type"/>
  <xs:element name="data" type="data-type"/>
  <xs:element name="wejscie" type="wejscie-type"/>
  <xs:element name="czas" type="czas-type"/>
  <xs:attribute name="popularno¶æ" type="shortString-type"/>
	
 	
  
<xs:complexType name="projekt-typ">
    <xs:sequence>
      <xs:element ref="autor"/>		  
	  <xs:element ref="Wersy_dnia"/>
	  <xs:element ref="Mistrzowie"/>
	  <xs:element ref="Koncerty"/>	  
      <xs:element ref="Wykonawcy"/>
	  <xs:element ref="Kontakt" /> 	  
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="data-type">
	<xs:restriction base="xs:date">		
	</xs:restriction>
  </xs:simpleType>
  
	<xs:complexType name="autor-type">		
        <xs:sequence>
          <xs:element name="imie" type="xs:string"/>
          <xs:element name="nazwisko" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
  
  <xs:simpleType name="Informacje-type">
  <xs:restriction base="xs:string">
		<xs:minLength value="1"/>
		<xs:maxLength value="1000"/>
	</xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="edycja-type">
		<xs:restriction base="xs:int">
		<xs:minInclusive value="0" />		
		</xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="czas-type">
		<xs:restriction base="xs:time">			
		</xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="wejscie-type">
	<xs:restriction base="xs:token">
		<xs:enumeration value="Darmowe" />
		<xs:enumeration value="P³atne" />		
	</xs:restriction>
</xs:simpleType>
  
  
 <xs:complexType name="Wersy_dnia-type">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="Informacje" minOccurs="0"/>
			<xs:element name="wers" type="xs:string"/>			
		</xs:choice>		
  </xs:complexType>
  
   
   <xs:complexType name="Mistrzowie-type">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="Informacje" minOccurs="0"/>
			<xs:element name="zawodnik" type="zawodnik-type"/>			
		</xs:choice>
  </xs:complexType>
  
  <xs:complexType name="zawodnik-type">
		<xs:sequence>
			<xs:element name="nazwa" type="xs:string" maxOccurs="unbounded"/>			
		</xs:sequence>
		<xs:attribute name="rok" type="rok-type" use="required"/>
		<xs:attribute name="dzika_karta" type="dzika_karta-type" use="required"/>		
	</xs:complexType>
	
  <xs:simpleType name="rok-type">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="2003" />
			<xs:maxInclusive value="2200" />
		</xs:restriction>
</xs:simpleType>
  
  	<xs:simpleType name="dzika_karta-type">
		<xs:restriction base="xs:string">
			<xs:pattern value="tak|nie"/>
		</xs:restriction>
	</xs:simpleType>
  
  
  
  <xs:complexType name="Koncerty-type">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="Informacje" minOccurs="0"/>
			<xs:element name="festival" type="festivalklub-type"/>
			<xs:element name="klub" type="festivalklub-type"/>
		</xs:choice>
  </xs:complexType> 
  
  <xs:complexType name="festivalklub-type">
		<xs:sequence>
			<xs:element name="event" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="miejsce" type="xs:string"/>				
			<xs:element ref="data" /> 
			<xs:element ref="czas" /> 
			<xs:element ref="edycja" /> 
			<xs:element ref="wejscie" /> 			
			<xs:element name="bilet" type="bilet-type" maxOccurs="unbounded"/>
			<xs:element name="szatnia" type="szatnia-type" maxOccurs="unbounded"/>
			<xs:element name="razem" type="razem-type" maxOccurs="unbounded"/>
			<xs:element name="eventID" type="eventID-type" />				
		</xs:sequence>
		<xs:attribute ref="popularno¶æ"/>
		<xs:attribute name="zasiêg" type="shortString-type" use="required"/>
		<xs:attribute name="rozmiar" type="shortString-type" use="required"/>
	</xs:complexType>
  
	<xs:simpleType name="bilet-type">
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="1" />
		<xs:maxInclusive value="70" />
	</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="szatnia-type">
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="1" />
		<xs:maxInclusive value="20" />
	</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="razem-type">
	<xs:union memberTypes=" bilet-type szatnia-type" />
	</xs:simpleType>
	
	<xs:simpleType name="eventID-type">
	<xs:restriction>
		<xs:simpleType>
			<xs:list>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="99" />
					</xs:restriction>
				</xs:simpleType>
			</xs:list>
		</xs:simpleType>
		<xs:length value="6" />
	</xs:restriction>
	</xs:simpleType>

  <xs:complexType name="Wykonawcy-type">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="Informacje" minOccurs="0"/>
			<xs:element name="muzycy" type="muzycyproducenci-type"/>
			<xs:element name="producenci" type="muzycyproducenci-type"/>
		</xs:choice>
  </xs:complexType> 
  
	<xs:complexType name="muzycyproducenci-type">
		<xs:sequence>
			<xs:element name="nazwa" type="nazwa-type" maxOccurs="unbounded"/>
			<xs:element name="wytwornia" type="shortString-type"/>
			<xs:element name="wystepy" type="wystepy-type" minOccurs="0"/>
			<xs:element name="opis" type="opis-type" minOccurs="3" maxOccurs="unbounded"/>
			<xs:element name="zdjecie" type="zdjecie-type" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="linki" type="linki-type" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="data" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="gatunek" type="shortString-type" use="required"/>
		<xs:attribute name="dziedzina" type="freestyle_studio" default="freestyle"/>
		<xs:attribute name="aktywny_na_scenie" type="tak_nie" use="required"/>
		<xs:attribute ref="popularno¶æ"/>
	</xs:complexType>
	
	<xs:complexType name="nazwa-type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="artysta" type="shortString-type" use="required"/>
			</xs:extension>			
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="wystepy-type">
		<xs:sequence>
			<xs:element name="kolaboracje" type="kolaboracje-type" maxOccurs="unbounded"/>
			<xs:element name="wydarzenie" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="pochodzenie" type="pochodzenie-type"/>
		</xs:sequence>		
	</xs:complexType>
	
	<xs:complexType name="kolaboracje-type">
		<xs:sequence>
			<xs:element name="duet" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="grupa" type="xs:string" maxOccurs="unbounded"/>			
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="opis-type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="czego_dotyczy" type="shortString-type"/>
			</xs:extension>			
		</xs:simpleContent>		
	</xs:complexType>
	
	<xs:complexType name="linki-type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="href" type="xs:anyURI" use="required"/>
			</xs:extension>
		</xs:simpleContent>	
	</xs:complexType>
	
	<xs:complexType name="zdjecie-type">
		<xs:attribute name="zrodlo" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="pochodzenie-type">
		<xs:attribute name="jakie">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="polskie|zagraniczne"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>	

	<xs:simpleType name="freestyle_studio">
		<xs:restriction base="xs:string">
			<xs:pattern value="freestyle|studio"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tak_nie">
		<xs:restriction base="xs:string">
			<xs:pattern value="tak|nie"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="shortString-type">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="Kontakt-type">
		<xs:sequence>
			<xs:element ref="autor" minOccurs="0"/>
			<xs:element name="wydzia³" type="xs:string"/>
			<xs:element name="telefon" type="xs:int"/>
			<xs:element name="mail" type="xs:string"/>
		</xs:sequence>
  </xs:complexType> 	
</xs:schema>

=== Bart0l/Freestyle-XML-XSD/Freestyle.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<projekt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="Freestyle.xsd"> 
   <autor>
   <imie>Bartlomiej</imie>
   <nazwisko>Borzyszkowski</nazwisko>
   
   </autor> 
  <Wersy_dnia> 
		<Informacje>Wybrane wersy dzisiejszego dnia!</Informacje>	
		<wers> "a propos pracy: powiem Tobie jedno, kocie - wygrasz ze mn± jak Syzyf przejdzie na bezrobocie!"</wers>
		<wers> "Wpadam tu i znow bujam tym klubem. Jaki ogrodnik? Rymuje bez ogrodek!"</wers>
		<wers> "Rapuje ca³y czas, mam talent. On ma punche z komisu - uzywane."</wers>   
  </Wersy_dnia>
  
  <Mistrzowie>
	<Informacje>Najlepsi wolnostylowcy w kraju!</Informacje>
	<zawodnik rok="2015" dzika_karta="nie">
	<nazwa>Edzio</nazwa>
	</zawodnik>
	<zawodnik rok="2014" dzika_karta="tak">
	<nazwa>Edzio</nazwa>
	</zawodnik>
	<zawodnik rok="2013" dzika_karta="tak">
	<nazwa>Szyderca</nazwa>
	</zawodnik>
	<zawodnik rok="2012" dzika_karta="nie">
	<nazwa>Czeski</nazwa>
	</zawodnik>	
  </Mistrzowie>
  
  <Koncerty>
	<Informacje>Dowiedz siê wiecej na temat hip-hopu!</Informacje>
	<festival popularno¶æ="rosn±ca" zasiêg="ogólnopolski" rozmiar="olbrzymi">
	<event>Street Art Festival</event>	
	<miejsce>Gdansk</miejsce>	
	<data> 2017-11-02</data>
	<czas>15:30:00</czas>
	<edycja>5</edycja>
	<wejscie>Platne</wejscie>	
	<bilet>50</bilet>
	<szatnia>3</szatnia>
	<razem>53</razem>
	<eventID>36 5 73 5 46 37</eventID>
	</festival>
	<klub popularno¶æ="rosn±ca" zasiêg="lokalny" rozmiar="kameralny">
	<event>Prosto Trójmiasto Sfinks700</event>	
	<miejsce>Sopot</miejsce>		
	<data> 2017-08-03</data>
	<czas>20:30:00</czas>
	<edycja>2</edycja>
	<wejscie>P³atne</wejscie>
	<bilet>45</bilet>
	<szatnia>5</szatnia>
	<razem>50</razem>
	<eventID>1 27 13 4 5 48</eventID>
	</klub>
  </Koncerty>
  
  <Wykonawcy>	
	<Informacje>Przyk³adowi wykonawcy muzyczni</Informacje>
    <muzycy gatunek="rap" dziedzina="freestyle" aktywny_na_scenie="tak" popularno¶æ="rosn±ca">	
      <nazwa artysta="pseudonim">Edzio</nazwa>
      <nazwa artysta="prawdziwie">Piotr Bylina</nazwa>
      <wytwornia>Bozon Records</wytwornia>
      <wystepy>
		<kolaboracje>
		<duet>Edzio/Filipek</duet>
		<grupa>Microphone Masters</grupa>
		</kolaboracje>
        <wydarzenie>Wielka Bitwa Warszawska</wydarzenie>
        <wydarzenie>Hip-hop Kemp</wydarzenie>
        <wydarzenie>Bitwa o Mokotów</wydarzenie>
        <wydarzenie>Bitwa o Stoczniê</wydarzenie>
        <wydarzenie>Bitwa o Pitos</wydarzenie>
        <wydarzenie>Cypher Time vol. 5</wydarzenie>
        <wydarzenie>Street Art Festival</wydarzenie>
        <pochodzenie jakie="polskie" />		
      </wystepy>
      <opis czego_dotyczy="Ogólny">
		Dwukrotny mistrz WBW. Po raz pierwszy pas zdoby³ po pokonaniu Jêdrzeja w 2014 roku. Jego obrona mia³a miejsce w 2015 roku po bardzo wyrównanym finale z Pejterem.
        </opis>
      <opis czego_dotyczy="Szczegó³y">
        S³ynie z unikatowych wersów, które rzadko bywaj± wcze¶niej planowane. Czêsto nawi±zuje do mitologii greckiej, a tak¿e historii i literatury.
      </opis>
      <opis czego_dotyczy="Technika">
        Potrafi p³ywaæ po podk³adach w wyj±tkowy sposób. Jego znakiem rozpoznawyczym s± samplowane bity. Najlepiej odnajduje siê w trueschoolu.
      </opis>
      <zdjecie zrodlo="Gfx/ZdjecieEdzio1.png"/>
      <zdjecie zrodlo="Gfx/ZdjecieEdzio2.png"/>
      <zdjecie zrodlo="Gfx/ZdjecieEdzio3.png"/>
      <zdjecie zrodlo="Gfx/ZdjecieEdzio4.png"/>
      <linki href="https://www.facebook.com/Edzio-242914792742471/?fref=ts">https://www.facebook.com/Edzio-242914792742471/?fref=ts</linki>
      <linki href="http://genius.com/Edzio">http://genius.com/Edzio</linki>
      <linki href="http://www.popkiller.pl/tagi/edzio">http://www.popkiller.pl/tagi/edzio</linki>
      <linki href="http://bozonrecords.pl/pl/artysci/edzio/">http://bozonrecords.pl/pl/artysci/edzio/</linki>   
	  <data>2016-11-29</data>
   </muzycy >

    <muzycy gatunek="rap" dziedzina="studio" aktywny_na_scenie="tak" popularno¶æ="rosn±ca">
      <nazwa artysta="pseudonim">Sokó³</nazwa>
      <nazwa artysta="prawdziwie">Wojciech Sosnowski</nazwa>
      <wytwornia>Prosto</wytwornia>
      <wystepy>
		<kolaboracje>
		<duet>Sokó³/Marysia Starosta</duet>
		<grupa>ZIP Sk³ad</grupa>
		</kolaboracje>		
        <wydarzenie>FESTXVAL PROSTO Torwar Warszawa</wydarzenie>
        <wydarzenie>Hip-hop Kemp</wydarzenie>
        <wydarzenie>Street Art Festival</wydarzenie>
        <wydarzenie>Wroc³aw Hip Hop Festival</wydarzenie>
		<wydarzenie>Street Art Festival</wydarzenie>
		<wydarzenie>TOOBI Summer Fest</wydarzenie>
		<wydarzenie>Everytap x World Wide Warsaw: Sokó³ i Marysia</wydarzenie>
        <pochodzenie jakie="polskie" />
      </wystepy>
      <opis czego_dotyczy="Ogólny">
        Za³ozyciel i wspó³w³a¶ciciel wytwórni p³ytowej "Prosto". Znany z wystêpów w grupie muzycznej WWO oraz ZIP Sk³ad, a tak¿e z duetu Sokó³/Marysia Starosta. Cz³onek Akademii Fonograficznej ZPAV oraz dziennikarz muzyczny.
      </opis>
      <opis czego_dotyczy="Szczegó³y">
        Nazywany narratorem, gdzy¿ pisze szczere i proste wersy, z perspektywy osoby postronnej opisywanych wydarzeñ. Unika klasycznych puncheline'ów i wyznaje prawdziwie klasyczny, oldschoolowy styl.
      </opis>
      <opis czego_dotyczy="Technika">
        Proste i dosadne flow. Nie jest to najlepszy technicznie muzyk, aczkolwiek zapracowa³ na ogromny szacunek u s³uchaczy za wspó³tworzenie polskiej sceny oraz ogromny wk³ad w kulturê.
      </opis>
      <zdjecie zrodlo="Gfx/ZdjecieSokol1.png"></zdjecie>
      <zdjecie zrodlo="Gfx/ZdjecieSokol2.png"></zdjecie>
      <zdjecie zrodlo="Gfx/ZdjecieSokol3.png"></zdjecie>
      <zdjecie zrodlo="Gfx/ZdjecieSokol4.png"></zdjecie>
      <linki href="https://pl.wikipedia.org/wiki/Sok%C3%B3%C5%82_(raper)">https://pl.wikipedia.org/wiki/Sok%C3%B3%C5%82_(raper)</linki>
      <linki href="http://prosto.pl/label/prosto/artists/sokol-i-marysia-starosta/">http://prosto.pl/label/prosto/artists/sokol-i-marysia-starosta/</linki>
      <linki href="https://www.facebook.com/sokolimarysiastarosta/">https://www.facebook.com/sokolimarysiastarosta/</linki>
      <linki href="http://genius.com/artists/Soko-pl">http://genius.com/artists/Soko-pl</linki>
	  <data>2016-11-28</data>
    </muzycy>

    <producenci gatunek="rap" dziedzina="studio" aktywny_na_scenie="tak" popularno¶æ="malej±ca">
      <nazwa artysta="pseudonim">NOON</nazwa>
      <nazwa artysta="prawdziwie">Miko³aj Bugajak</nazwa>
      <wytwornia>Nowe Nagrania</wytwornia>
      <wystepy>
		<kolaboracje>
		<duet>Pezet/NOON</duet>
		<grupa>Grammatik</grupa>
		</kolaboracje>		
        <wydarzenie>Grammatik / ¦wiat³a Miasta / Warszawa</wydarzenie>
        <wydarzenie>HV/NOON</wydarzenie>
        <wydarzenie>Pitu Pitu Warszawa</wydarzenie>        
		<wydarzenie>Basen Artystyczny / Opera OFF </wydarzenie>
		<wydarzenie>Everytap x World Wide Warsaw: Sokó³ i Marysia</wydarzenie>
        <pochodzenie jakie="polskie" />
      </wystepy>
      <opis czego_dotyczy="Ogólny">
        NOON ma na koncie przynajmniej kilka p³yt, które zas³u¿y³y na miano klasycznych. S³yn±cy z nieszablonowego podej¶cia do muzyki rozpocz±³ karierê jako producent muzyczny, tworz±c sukces takich artystów jak Grammatik oraz Pezet.
		</opis>  
	  <opis czego_dotyczy="Szczegó³y">
		Muzyk i kompozytor, instrumentalista, a tak¿e producent muzyczny i in¿ynier d¼wiêku, specjalista z zakresu masteringu. W³a¶ciciel studia 33 Obroty oraz wspó³za³o¿yciel studia S-33.
        </opis>
      <opis czego_dotyczy="Technika">
		Jeden z najwybitniejszych hip-hopowych producentów. Droga od instrumentalnego rapu, przez muzykê elektroniczn±, a¿ do kompozycji akustycznych odby³a siê p³ynnie g³ównie za spraw± charakterystycznego brzmienia, które jest jego wizytówk±.
         </opis>
      <zdjecie zrodlo="Gfx/ZdjecieNOON1.png"></zdjecie>
      <zdjecie zrodlo="Gfx/ZdjecieNOON2.png"></zdjecie>
      <zdjecie zrodlo="Gfx/ZdjecieNOON3.png"></zdjecie>
      <zdjecie zrodlo="Gfx/ZdjecieNOON4.png"></zdjecie>
	  <linki href="https://pl.wikipedia.org/wiki/Noon">https://pl.wikipedia.org/wiki/Noon</linki>
      <linki href="https://www.facebook.com/pg/MikolajBugajak/about/?ref=page_internal">https://www.facebook.com/pg/MikolajBugajak/about/?ref=page_internal</linki>
      <linki href="http://www.asfalt.pl/noon.html">http://www.asfalt.pl/noon.html</linki>
      <linki href="http://www.newsweek.pl/kultura/wywiad-z-noon-em-wciaz-nie-odnalazlem-tego-czego-szukam-nesweek-pl,artykuly,354006,1.html">http://www.newsweek.pl/kultura/wywiad-z-noon-em-wciaz-nie-odnalazlem-tego-czego-szukam-nesweek-pl,artykuly,354006,1.html</linki>
	  <data>2016-11-27</data>
   </producenci>
  </Wykonawcy>
  
  <Kontakt>
	<autor>   
	<imie>Bart³omiej</imie>
	<nazwisko>Borzyszkowski</nazwisko>
	</autor>
	<wydzia³> WETI </wydzia³>
	<telefon> 661502301 </telefon>
	<mail> bartek.borzyszkowski@wp.pl </mail>
  </Kontakt>
  
  
</projekt>
